// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: decision.proto

#ifndef PROTOBUF_INCLUDED_decision_2eproto
#define PROTOBUF_INCLUDED_decision_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_decision_2eproto 

namespace protobuf_decision_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_decision_2eproto
namespace roborts_decision {
class DecisionConfig;
class DecisionConfigDefaultTypeInternal;
extern DecisionConfigDefaultTypeInternal _DecisionConfig_default_instance_;
class EscapeConstraint;
class EscapeConstraintDefaultTypeInternal;
extern EscapeConstraintDefaultTypeInternal _EscapeConstraint_default_instance_;
class MultiRobot;
class MultiRobotDefaultTypeInternal;
extern MultiRobotDefaultTypeInternal _MultiRobot_default_instance_;
class Point;
class PointDefaultTypeInternal;
extern PointDefaultTypeInternal _Point_default_instance_;
class SearchConstraint;
class SearchConstraintDefaultTypeInternal;
extern SearchConstraintDefaultTypeInternal _SearchConstraint_default_instance_;
class WhirlVel;
class WhirlVelDefaultTypeInternal;
extern WhirlVelDefaultTypeInternal _WhirlVel_default_instance_;
}  // namespace roborts_decision
namespace google {
namespace protobuf {
template<> ::roborts_decision::DecisionConfig* Arena::CreateMaybeMessage<::roborts_decision::DecisionConfig>(Arena*);
template<> ::roborts_decision::EscapeConstraint* Arena::CreateMaybeMessage<::roborts_decision::EscapeConstraint>(Arena*);
template<> ::roborts_decision::MultiRobot* Arena::CreateMaybeMessage<::roborts_decision::MultiRobot>(Arena*);
template<> ::roborts_decision::Point* Arena::CreateMaybeMessage<::roborts_decision::Point>(Arena*);
template<> ::roborts_decision::SearchConstraint* Arena::CreateMaybeMessage<::roborts_decision::SearchConstraint>(Arena*);
template<> ::roborts_decision::WhirlVel* Arena::CreateMaybeMessage<::roborts_decision::WhirlVel>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace roborts_decision {

// ===================================================================

class Point : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:roborts_decision.Point) */ {
 public:
  Point();
  virtual ~Point();

  Point(const Point& from);

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Point(Point&& from) noexcept
    : Point() {
    *this = ::std::move(from);
  }

  inline Point& operator=(Point&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Point& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Point* internal_default_instance() {
    return reinterpret_cast<const Point*>(
               &_Point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Point* other);
  friend void swap(Point& a, Point& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Point* New() const final {
    return CreateMaybeMessage<Point>(NULL);
  }

  Point* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Point>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Point& from);
  void MergeFrom(const Point& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // optional float y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // optional float z = 3;
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // optional float roll = 4;
  bool has_roll() const;
  void clear_roll();
  static const int kRollFieldNumber = 4;
  float roll() const;
  void set_roll(float value);

  // optional float pitch = 5;
  bool has_pitch() const;
  void clear_pitch();
  static const int kPitchFieldNumber = 5;
  float pitch() const;
  void set_pitch(float value);

  // optional float yaw = 6;
  bool has_yaw() const;
  void clear_yaw();
  static const int kYawFieldNumber = 6;
  float yaw() const;
  void set_yaw(float value);

  // @@protoc_insertion_point(class_scope:roborts_decision.Point)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_z();
  void clear_has_z();
  void set_has_roll();
  void clear_has_roll();
  void set_has_pitch();
  void clear_has_pitch();
  void set_has_yaw();
  void clear_has_yaw();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  float x_;
  float y_;
  float z_;
  float roll_;
  float pitch_;
  float yaw_;
  friend struct ::protobuf_decision_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class EscapeConstraint : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:roborts_decision.EscapeConstraint) */ {
 public:
  EscapeConstraint();
  virtual ~EscapeConstraint();

  EscapeConstraint(const EscapeConstraint& from);

  inline EscapeConstraint& operator=(const EscapeConstraint& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  EscapeConstraint(EscapeConstraint&& from) noexcept
    : EscapeConstraint() {
    *this = ::std::move(from);
  }

  inline EscapeConstraint& operator=(EscapeConstraint&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EscapeConstraint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EscapeConstraint* internal_default_instance() {
    return reinterpret_cast<const EscapeConstraint*>(
               &_EscapeConstraint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(EscapeConstraint* other);
  friend void swap(EscapeConstraint& a, EscapeConstraint& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline EscapeConstraint* New() const final {
    return CreateMaybeMessage<EscapeConstraint>(NULL);
  }

  EscapeConstraint* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<EscapeConstraint>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const EscapeConstraint& from);
  void MergeFrom(const EscapeConstraint& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EscapeConstraint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float left_x_limit = 1;
  bool has_left_x_limit() const;
  void clear_left_x_limit();
  static const int kLeftXLimitFieldNumber = 1;
  float left_x_limit() const;
  void set_left_x_limit(float value);

  // optional float right_x_limit = 2;
  bool has_right_x_limit() const;
  void clear_right_x_limit();
  static const int kRightXLimitFieldNumber = 2;
  float right_x_limit() const;
  void set_right_x_limit(float value);

  // optional float robot_x_limit = 3;
  bool has_robot_x_limit() const;
  void clear_robot_x_limit();
  static const int kRobotXLimitFieldNumber = 3;
  float robot_x_limit() const;
  void set_robot_x_limit(float value);

  // optional float left_random_min_x = 4;
  bool has_left_random_min_x() const;
  void clear_left_random_min_x();
  static const int kLeftRandomMinXFieldNumber = 4;
  float left_random_min_x() const;
  void set_left_random_min_x(float value);

  // optional float left_random_max_x = 5;
  bool has_left_random_max_x() const;
  void clear_left_random_max_x();
  static const int kLeftRandomMaxXFieldNumber = 5;
  float left_random_max_x() const;
  void set_left_random_max_x(float value);

  // optional float right_random_min_x = 6;
  bool has_right_random_min_x() const;
  void clear_right_random_min_x();
  static const int kRightRandomMinXFieldNumber = 6;
  float right_random_min_x() const;
  void set_right_random_min_x(float value);

  // optional float right_random_max_x = 7;
  bool has_right_random_max_x() const;
  void clear_right_random_max_x();
  static const int kRightRandomMaxXFieldNumber = 7;
  float right_random_max_x() const;
  void set_right_random_max_x(float value);

  // @@protoc_insertion_point(class_scope:roborts_decision.EscapeConstraint)
 private:
  void set_has_left_x_limit();
  void clear_has_left_x_limit();
  void set_has_right_x_limit();
  void clear_has_right_x_limit();
  void set_has_robot_x_limit();
  void clear_has_robot_x_limit();
  void set_has_left_random_min_x();
  void clear_has_left_random_min_x();
  void set_has_left_random_max_x();
  void clear_has_left_random_max_x();
  void set_has_right_random_min_x();
  void clear_has_right_random_min_x();
  void set_has_right_random_max_x();
  void clear_has_right_random_max_x();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  float left_x_limit_;
  float right_x_limit_;
  float robot_x_limit_;
  float left_random_min_x_;
  float left_random_max_x_;
  float right_random_min_x_;
  float right_random_max_x_;
  friend struct ::protobuf_decision_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SearchConstraint : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:roborts_decision.SearchConstraint) */ {
 public:
  SearchConstraint();
  virtual ~SearchConstraint();

  SearchConstraint(const SearchConstraint& from);

  inline SearchConstraint& operator=(const SearchConstraint& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SearchConstraint(SearchConstraint&& from) noexcept
    : SearchConstraint() {
    *this = ::std::move(from);
  }

  inline SearchConstraint& operator=(SearchConstraint&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SearchConstraint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SearchConstraint* internal_default_instance() {
    return reinterpret_cast<const SearchConstraint*>(
               &_SearchConstraint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(SearchConstraint* other);
  friend void swap(SearchConstraint& a, SearchConstraint& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SearchConstraint* New() const final {
    return CreateMaybeMessage<SearchConstraint>(NULL);
  }

  SearchConstraint* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SearchConstraint>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SearchConstraint& from);
  void MergeFrom(const SearchConstraint& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SearchConstraint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float x_limit = 1;
  bool has_x_limit() const;
  void clear_x_limit();
  static const int kXLimitFieldNumber = 1;
  float x_limit() const;
  void set_x_limit(float value);

  // optional float y_limit = 2;
  bool has_y_limit() const;
  void clear_y_limit();
  static const int kYLimitFieldNumber = 2;
  float y_limit() const;
  void set_y_limit(float value);

  // @@protoc_insertion_point(class_scope:roborts_decision.SearchConstraint)
 private:
  void set_has_x_limit();
  void clear_has_x_limit();
  void set_has_y_limit();
  void clear_has_y_limit();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  float x_limit_;
  float y_limit_;
  friend struct ::protobuf_decision_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class WhirlVel : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:roborts_decision.WhirlVel) */ {
 public:
  WhirlVel();
  virtual ~WhirlVel();

  WhirlVel(const WhirlVel& from);

  inline WhirlVel& operator=(const WhirlVel& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  WhirlVel(WhirlVel&& from) noexcept
    : WhirlVel() {
    *this = ::std::move(from);
  }

  inline WhirlVel& operator=(WhirlVel&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WhirlVel& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WhirlVel* internal_default_instance() {
    return reinterpret_cast<const WhirlVel*>(
               &_WhirlVel_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(WhirlVel* other);
  friend void swap(WhirlVel& a, WhirlVel& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WhirlVel* New() const final {
    return CreateMaybeMessage<WhirlVel>(NULL);
  }

  WhirlVel* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<WhirlVel>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const WhirlVel& from);
  void MergeFrom(const WhirlVel& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WhirlVel* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float angle_x_vel = 1;
  bool has_angle_x_vel() const;
  void clear_angle_x_vel();
  static const int kAngleXVelFieldNumber = 1;
  float angle_x_vel() const;
  void set_angle_x_vel(float value);

  // optional float angle_y_vel = 2;
  bool has_angle_y_vel() const;
  void clear_angle_y_vel();
  static const int kAngleYVelFieldNumber = 2;
  float angle_y_vel() const;
  void set_angle_y_vel(float value);

  // optional float angle_z_vel = 3;
  bool has_angle_z_vel() const;
  void clear_angle_z_vel();
  static const int kAngleZVelFieldNumber = 3;
  float angle_z_vel() const;
  void set_angle_z_vel(float value);

  // @@protoc_insertion_point(class_scope:roborts_decision.WhirlVel)
 private:
  void set_has_angle_x_vel();
  void clear_has_angle_x_vel();
  void set_has_angle_y_vel();
  void clear_has_angle_y_vel();
  void set_has_angle_z_vel();
  void clear_has_angle_z_vel();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  float angle_x_vel_;
  float angle_y_vel_;
  float angle_z_vel_;
  friend struct ::protobuf_decision_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MultiRobot : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:roborts_decision.MultiRobot) */ {
 public:
  MultiRobot();
  virtual ~MultiRobot();

  MultiRobot(const MultiRobot& from);

  inline MultiRobot& operator=(const MultiRobot& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MultiRobot(MultiRobot&& from) noexcept
    : MultiRobot() {
    *this = ::std::move(from);
  }

  inline MultiRobot& operator=(MultiRobot&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MultiRobot& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MultiRobot* internal_default_instance() {
    return reinterpret_cast<const MultiRobot*>(
               &_MultiRobot_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(MultiRobot* other);
  friend void swap(MultiRobot& a, MultiRobot& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MultiRobot* New() const final {
    return CreateMaybeMessage<MultiRobot>(NULL);
  }

  MultiRobot* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MultiRobot>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MultiRobot& from);
  void MergeFrom(const MultiRobot& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MultiRobot* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .roborts_decision.Point start_position = 7;
  bool has_start_position() const;
  void clear_start_position();
  static const int kStartPositionFieldNumber = 7;
  private:
  const ::roborts_decision::Point& _internal_start_position() const;
  public:
  const ::roborts_decision::Point& start_position() const;
  ::roborts_decision::Point* release_start_position();
  ::roborts_decision::Point* mutable_start_position();
  void set_allocated_start_position(::roborts_decision::Point* start_position);

  // @@protoc_insertion_point(class_scope:roborts_decision.MultiRobot)
 private:
  void set_has_start_position();
  void clear_has_start_position();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::roborts_decision::Point* start_position_;
  friend struct ::protobuf_decision_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DecisionConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:roborts_decision.DecisionConfig) */ {
 public:
  DecisionConfig();
  virtual ~DecisionConfig();

  DecisionConfig(const DecisionConfig& from);

  inline DecisionConfig& operator=(const DecisionConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DecisionConfig(DecisionConfig&& from) noexcept
    : DecisionConfig() {
    *this = ::std::move(from);
  }

  inline DecisionConfig& operator=(DecisionConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DecisionConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DecisionConfig* internal_default_instance() {
    return reinterpret_cast<const DecisionConfig*>(
               &_DecisionConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(DecisionConfig* other);
  friend void swap(DecisionConfig& a, DecisionConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DecisionConfig* New() const final {
    return CreateMaybeMessage<DecisionConfig>(NULL);
  }

  DecisionConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DecisionConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DecisionConfig& from);
  void MergeFrom(const DecisionConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DecisionConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .roborts_decision.Point point = 1;
  int point_size() const;
  void clear_point();
  static const int kPointFieldNumber = 1;
  ::roborts_decision::Point* mutable_point(int index);
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
      mutable_point();
  const ::roborts_decision::Point& point(int index) const;
  ::roborts_decision::Point* add_point();
  const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
      point() const;

  // repeated .roborts_decision.Point buff_point = 5;
  int buff_point_size() const;
  void clear_buff_point();
  static const int kBuffPointFieldNumber = 5;
  ::roborts_decision::Point* mutable_buff_point(int index);
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
      mutable_buff_point();
  const ::roborts_decision::Point& buff_point(int index) const;
  ::roborts_decision::Point* add_buff_point();
  const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
      buff_point() const;

  // repeated .roborts_decision.Point search_region_1 = 11;
  int search_region_1_size() const;
  void clear_search_region_1();
  static const int kSearchRegion1FieldNumber = 11;
  ::roborts_decision::Point* mutable_search_region_1(int index);
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
      mutable_search_region_1();
  const ::roborts_decision::Point& search_region_1(int index) const;
  ::roborts_decision::Point* add_search_region_1();
  const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
      search_region_1() const;

  // repeated .roborts_decision.Point search_region_2 = 12;
  int search_region_2_size() const;
  void clear_search_region_2();
  static const int kSearchRegion2FieldNumber = 12;
  ::roborts_decision::Point* mutable_search_region_2(int index);
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
      mutable_search_region_2();
  const ::roborts_decision::Point& search_region_2(int index) const;
  ::roborts_decision::Point* add_search_region_2();
  const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
      search_region_2() const;

  // repeated .roborts_decision.Point search_region_3 = 13;
  int search_region_3_size() const;
  void clear_search_region_3();
  static const int kSearchRegion3FieldNumber = 13;
  ::roborts_decision::Point* mutable_search_region_3(int index);
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
      mutable_search_region_3();
  const ::roborts_decision::Point& search_region_3(int index) const;
  ::roborts_decision::Point* add_search_region_3();
  const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
      search_region_3() const;

  // repeated .roborts_decision.Point search_region_4 = 14;
  int search_region_4_size() const;
  void clear_search_region_4();
  static const int kSearchRegion4FieldNumber = 14;
  ::roborts_decision::Point* mutable_search_region_4(int index);
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
      mutable_search_region_4();
  const ::roborts_decision::Point& search_region_4(int index) const;
  ::roborts_decision::Point* add_search_region_4();
  const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
      search_region_4() const;

  // optional .roborts_decision.EscapeConstraint escape = 4;
  bool has_escape() const;
  void clear_escape();
  static const int kEscapeFieldNumber = 4;
  private:
  const ::roborts_decision::EscapeConstraint& _internal_escape() const;
  public:
  const ::roborts_decision::EscapeConstraint& escape() const;
  ::roborts_decision::EscapeConstraint* release_escape();
  ::roborts_decision::EscapeConstraint* mutable_escape();
  void set_allocated_escape(::roborts_decision::EscapeConstraint* escape);

  // optional .roborts_decision.SearchConstraint search_limit = 6;
  bool has_search_limit() const;
  void clear_search_limit();
  static const int kSearchLimitFieldNumber = 6;
  private:
  const ::roborts_decision::SearchConstraint& _internal_search_limit() const;
  public:
  const ::roborts_decision::SearchConstraint& search_limit() const;
  ::roborts_decision::SearchConstraint* release_search_limit();
  ::roborts_decision::SearchConstraint* mutable_search_limit();
  void set_allocated_search_limit(::roborts_decision::SearchConstraint* search_limit);

  // optional .roborts_decision.WhirlVel whirl_vel = 7;
  bool has_whirl_vel() const;
  void clear_whirl_vel();
  static const int kWhirlVelFieldNumber = 7;
  private:
  const ::roborts_decision::WhirlVel& _internal_whirl_vel() const;
  public:
  const ::roborts_decision::WhirlVel& whirl_vel() const;
  ::roborts_decision::WhirlVel* release_whirl_vel();
  ::roborts_decision::WhirlVel* mutable_whirl_vel();
  void set_allocated_whirl_vel(::roborts_decision::WhirlVel* whirl_vel);

  // optional .roborts_decision.MultiRobot wing_bot = 8;
  bool has_wing_bot() const;
  void clear_wing_bot();
  static const int kWingBotFieldNumber = 8;
  private:
  const ::roborts_decision::MultiRobot& _internal_wing_bot() const;
  public:
  const ::roborts_decision::MultiRobot& wing_bot() const;
  ::roborts_decision::MultiRobot* release_wing_bot();
  ::roborts_decision::MultiRobot* mutable_wing_bot();
  void set_allocated_wing_bot(::roborts_decision::MultiRobot* wing_bot);

  // optional .roborts_decision.MultiRobot master_bot = 9;
  bool has_master_bot() const;
  void clear_master_bot();
  static const int kMasterBotFieldNumber = 9;
  private:
  const ::roborts_decision::MultiRobot& _internal_master_bot() const;
  public:
  const ::roborts_decision::MultiRobot& master_bot() const;
  ::roborts_decision::MultiRobot* release_master_bot();
  ::roborts_decision::MultiRobot* mutable_master_bot();
  void set_allocated_master_bot(::roborts_decision::MultiRobot* master_bot);

  // optional .roborts_decision.Point wing_bot_task_point = 10;
  bool has_wing_bot_task_point() const;
  void clear_wing_bot_task_point();
  static const int kWingBotTaskPointFieldNumber = 10;
  private:
  const ::roborts_decision::Point& _internal_wing_bot_task_point() const;
  public:
  const ::roborts_decision::Point& wing_bot_task_point() const;
  ::roborts_decision::Point* release_wing_bot_task_point();
  ::roborts_decision::Point* mutable_wing_bot_task_point();
  void set_allocated_wing_bot_task_point(::roborts_decision::Point* wing_bot_task_point);

  // optional bool simulate = 2 [default = false];
  bool has_simulate() const;
  void clear_simulate();
  static const int kSimulateFieldNumber = 2;
  bool simulate() const;
  void set_simulate(bool value);

  // optional bool master = 3 [default = false];
  bool has_master() const;
  void clear_master();
  static const int kMasterFieldNumber = 3;
  bool master() const;
  void set_master(bool value);

  // @@protoc_insertion_point(class_scope:roborts_decision.DecisionConfig)
 private:
  void set_has_simulate();
  void clear_has_simulate();
  void set_has_master();
  void clear_has_master();
  void set_has_escape();
  void clear_has_escape();
  void set_has_search_limit();
  void clear_has_search_limit();
  void set_has_whirl_vel();
  void clear_has_whirl_vel();
  void set_has_wing_bot();
  void clear_has_wing_bot();
  void set_has_master_bot();
  void clear_has_master_bot();
  void set_has_wing_bot_task_point();
  void clear_has_wing_bot_task_point();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point > point_;
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point > buff_point_;
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point > search_region_1_;
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point > search_region_2_;
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point > search_region_3_;
  ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point > search_region_4_;
  ::roborts_decision::EscapeConstraint* escape_;
  ::roborts_decision::SearchConstraint* search_limit_;
  ::roborts_decision::WhirlVel* whirl_vel_;
  ::roborts_decision::MultiRobot* wing_bot_;
  ::roborts_decision::MultiRobot* master_bot_;
  ::roborts_decision::Point* wing_bot_task_point_;
  bool simulate_;
  bool master_;
  friend struct ::protobuf_decision_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Point

// optional float x = 1;
inline bool Point::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Point::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Point::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Point::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float Point::x() const {
  // @@protoc_insertion_point(field_get:roborts_decision.Point.x)
  return x_;
}
inline void Point::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.Point.x)
}

// optional float y = 2;
inline bool Point::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Point::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Point::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Point::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float Point::y() const {
  // @@protoc_insertion_point(field_get:roborts_decision.Point.y)
  return y_;
}
inline void Point::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.Point.y)
}

// optional float z = 3;
inline bool Point::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Point::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Point::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Point::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline float Point::z() const {
  // @@protoc_insertion_point(field_get:roborts_decision.Point.z)
  return z_;
}
inline void Point::set_z(float value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.Point.z)
}

// optional float roll = 4;
inline bool Point::has_roll() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Point::set_has_roll() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Point::clear_has_roll() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Point::clear_roll() {
  roll_ = 0;
  clear_has_roll();
}
inline float Point::roll() const {
  // @@protoc_insertion_point(field_get:roborts_decision.Point.roll)
  return roll_;
}
inline void Point::set_roll(float value) {
  set_has_roll();
  roll_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.Point.roll)
}

// optional float pitch = 5;
inline bool Point::has_pitch() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Point::set_has_pitch() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Point::clear_has_pitch() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Point::clear_pitch() {
  pitch_ = 0;
  clear_has_pitch();
}
inline float Point::pitch() const {
  // @@protoc_insertion_point(field_get:roborts_decision.Point.pitch)
  return pitch_;
}
inline void Point::set_pitch(float value) {
  set_has_pitch();
  pitch_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.Point.pitch)
}

// optional float yaw = 6;
inline bool Point::has_yaw() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Point::set_has_yaw() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Point::clear_has_yaw() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Point::clear_yaw() {
  yaw_ = 0;
  clear_has_yaw();
}
inline float Point::yaw() const {
  // @@protoc_insertion_point(field_get:roborts_decision.Point.yaw)
  return yaw_;
}
inline void Point::set_yaw(float value) {
  set_has_yaw();
  yaw_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.Point.yaw)
}

// -------------------------------------------------------------------

// EscapeConstraint

// optional float left_x_limit = 1;
inline bool EscapeConstraint::has_left_x_limit() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EscapeConstraint::set_has_left_x_limit() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EscapeConstraint::clear_has_left_x_limit() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EscapeConstraint::clear_left_x_limit() {
  left_x_limit_ = 0;
  clear_has_left_x_limit();
}
inline float EscapeConstraint::left_x_limit() const {
  // @@protoc_insertion_point(field_get:roborts_decision.EscapeConstraint.left_x_limit)
  return left_x_limit_;
}
inline void EscapeConstraint::set_left_x_limit(float value) {
  set_has_left_x_limit();
  left_x_limit_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.EscapeConstraint.left_x_limit)
}

// optional float right_x_limit = 2;
inline bool EscapeConstraint::has_right_x_limit() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void EscapeConstraint::set_has_right_x_limit() {
  _has_bits_[0] |= 0x00000002u;
}
inline void EscapeConstraint::clear_has_right_x_limit() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void EscapeConstraint::clear_right_x_limit() {
  right_x_limit_ = 0;
  clear_has_right_x_limit();
}
inline float EscapeConstraint::right_x_limit() const {
  // @@protoc_insertion_point(field_get:roborts_decision.EscapeConstraint.right_x_limit)
  return right_x_limit_;
}
inline void EscapeConstraint::set_right_x_limit(float value) {
  set_has_right_x_limit();
  right_x_limit_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.EscapeConstraint.right_x_limit)
}

// optional float robot_x_limit = 3;
inline bool EscapeConstraint::has_robot_x_limit() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void EscapeConstraint::set_has_robot_x_limit() {
  _has_bits_[0] |= 0x00000004u;
}
inline void EscapeConstraint::clear_has_robot_x_limit() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void EscapeConstraint::clear_robot_x_limit() {
  robot_x_limit_ = 0;
  clear_has_robot_x_limit();
}
inline float EscapeConstraint::robot_x_limit() const {
  // @@protoc_insertion_point(field_get:roborts_decision.EscapeConstraint.robot_x_limit)
  return robot_x_limit_;
}
inline void EscapeConstraint::set_robot_x_limit(float value) {
  set_has_robot_x_limit();
  robot_x_limit_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.EscapeConstraint.robot_x_limit)
}

// optional float left_random_min_x = 4;
inline bool EscapeConstraint::has_left_random_min_x() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void EscapeConstraint::set_has_left_random_min_x() {
  _has_bits_[0] |= 0x00000008u;
}
inline void EscapeConstraint::clear_has_left_random_min_x() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void EscapeConstraint::clear_left_random_min_x() {
  left_random_min_x_ = 0;
  clear_has_left_random_min_x();
}
inline float EscapeConstraint::left_random_min_x() const {
  // @@protoc_insertion_point(field_get:roborts_decision.EscapeConstraint.left_random_min_x)
  return left_random_min_x_;
}
inline void EscapeConstraint::set_left_random_min_x(float value) {
  set_has_left_random_min_x();
  left_random_min_x_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.EscapeConstraint.left_random_min_x)
}

// optional float left_random_max_x = 5;
inline bool EscapeConstraint::has_left_random_max_x() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void EscapeConstraint::set_has_left_random_max_x() {
  _has_bits_[0] |= 0x00000010u;
}
inline void EscapeConstraint::clear_has_left_random_max_x() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void EscapeConstraint::clear_left_random_max_x() {
  left_random_max_x_ = 0;
  clear_has_left_random_max_x();
}
inline float EscapeConstraint::left_random_max_x() const {
  // @@protoc_insertion_point(field_get:roborts_decision.EscapeConstraint.left_random_max_x)
  return left_random_max_x_;
}
inline void EscapeConstraint::set_left_random_max_x(float value) {
  set_has_left_random_max_x();
  left_random_max_x_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.EscapeConstraint.left_random_max_x)
}

// optional float right_random_min_x = 6;
inline bool EscapeConstraint::has_right_random_min_x() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void EscapeConstraint::set_has_right_random_min_x() {
  _has_bits_[0] |= 0x00000020u;
}
inline void EscapeConstraint::clear_has_right_random_min_x() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void EscapeConstraint::clear_right_random_min_x() {
  right_random_min_x_ = 0;
  clear_has_right_random_min_x();
}
inline float EscapeConstraint::right_random_min_x() const {
  // @@protoc_insertion_point(field_get:roborts_decision.EscapeConstraint.right_random_min_x)
  return right_random_min_x_;
}
inline void EscapeConstraint::set_right_random_min_x(float value) {
  set_has_right_random_min_x();
  right_random_min_x_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.EscapeConstraint.right_random_min_x)
}

// optional float right_random_max_x = 7;
inline bool EscapeConstraint::has_right_random_max_x() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void EscapeConstraint::set_has_right_random_max_x() {
  _has_bits_[0] |= 0x00000040u;
}
inline void EscapeConstraint::clear_has_right_random_max_x() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void EscapeConstraint::clear_right_random_max_x() {
  right_random_max_x_ = 0;
  clear_has_right_random_max_x();
}
inline float EscapeConstraint::right_random_max_x() const {
  // @@protoc_insertion_point(field_get:roborts_decision.EscapeConstraint.right_random_max_x)
  return right_random_max_x_;
}
inline void EscapeConstraint::set_right_random_max_x(float value) {
  set_has_right_random_max_x();
  right_random_max_x_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.EscapeConstraint.right_random_max_x)
}

// -------------------------------------------------------------------

// SearchConstraint

// optional float x_limit = 1;
inline bool SearchConstraint::has_x_limit() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SearchConstraint::set_has_x_limit() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SearchConstraint::clear_has_x_limit() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SearchConstraint::clear_x_limit() {
  x_limit_ = 0;
  clear_has_x_limit();
}
inline float SearchConstraint::x_limit() const {
  // @@protoc_insertion_point(field_get:roborts_decision.SearchConstraint.x_limit)
  return x_limit_;
}
inline void SearchConstraint::set_x_limit(float value) {
  set_has_x_limit();
  x_limit_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.SearchConstraint.x_limit)
}

// optional float y_limit = 2;
inline bool SearchConstraint::has_y_limit() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SearchConstraint::set_has_y_limit() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SearchConstraint::clear_has_y_limit() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SearchConstraint::clear_y_limit() {
  y_limit_ = 0;
  clear_has_y_limit();
}
inline float SearchConstraint::y_limit() const {
  // @@protoc_insertion_point(field_get:roborts_decision.SearchConstraint.y_limit)
  return y_limit_;
}
inline void SearchConstraint::set_y_limit(float value) {
  set_has_y_limit();
  y_limit_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.SearchConstraint.y_limit)
}

// -------------------------------------------------------------------

// WhirlVel

// optional float angle_x_vel = 1;
inline bool WhirlVel::has_angle_x_vel() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WhirlVel::set_has_angle_x_vel() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WhirlVel::clear_has_angle_x_vel() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WhirlVel::clear_angle_x_vel() {
  angle_x_vel_ = 0;
  clear_has_angle_x_vel();
}
inline float WhirlVel::angle_x_vel() const {
  // @@protoc_insertion_point(field_get:roborts_decision.WhirlVel.angle_x_vel)
  return angle_x_vel_;
}
inline void WhirlVel::set_angle_x_vel(float value) {
  set_has_angle_x_vel();
  angle_x_vel_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.WhirlVel.angle_x_vel)
}

// optional float angle_y_vel = 2;
inline bool WhirlVel::has_angle_y_vel() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WhirlVel::set_has_angle_y_vel() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WhirlVel::clear_has_angle_y_vel() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void WhirlVel::clear_angle_y_vel() {
  angle_y_vel_ = 0;
  clear_has_angle_y_vel();
}
inline float WhirlVel::angle_y_vel() const {
  // @@protoc_insertion_point(field_get:roborts_decision.WhirlVel.angle_y_vel)
  return angle_y_vel_;
}
inline void WhirlVel::set_angle_y_vel(float value) {
  set_has_angle_y_vel();
  angle_y_vel_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.WhirlVel.angle_y_vel)
}

// optional float angle_z_vel = 3;
inline bool WhirlVel::has_angle_z_vel() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void WhirlVel::set_has_angle_z_vel() {
  _has_bits_[0] |= 0x00000004u;
}
inline void WhirlVel::clear_has_angle_z_vel() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void WhirlVel::clear_angle_z_vel() {
  angle_z_vel_ = 0;
  clear_has_angle_z_vel();
}
inline float WhirlVel::angle_z_vel() const {
  // @@protoc_insertion_point(field_get:roborts_decision.WhirlVel.angle_z_vel)
  return angle_z_vel_;
}
inline void WhirlVel::set_angle_z_vel(float value) {
  set_has_angle_z_vel();
  angle_z_vel_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.WhirlVel.angle_z_vel)
}

// -------------------------------------------------------------------

// MultiRobot

// optional .roborts_decision.Point start_position = 7;
inline bool MultiRobot::has_start_position() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MultiRobot::set_has_start_position() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MultiRobot::clear_has_start_position() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MultiRobot::clear_start_position() {
  if (start_position_ != NULL) start_position_->Clear();
  clear_has_start_position();
}
inline const ::roborts_decision::Point& MultiRobot::_internal_start_position() const {
  return *start_position_;
}
inline const ::roborts_decision::Point& MultiRobot::start_position() const {
  const ::roborts_decision::Point* p = start_position_;
  // @@protoc_insertion_point(field_get:roborts_decision.MultiRobot.start_position)
  return p != NULL ? *p : *reinterpret_cast<const ::roborts_decision::Point*>(
      &::roborts_decision::_Point_default_instance_);
}
inline ::roborts_decision::Point* MultiRobot::release_start_position() {
  // @@protoc_insertion_point(field_release:roborts_decision.MultiRobot.start_position)
  clear_has_start_position();
  ::roborts_decision::Point* temp = start_position_;
  start_position_ = NULL;
  return temp;
}
inline ::roborts_decision::Point* MultiRobot::mutable_start_position() {
  set_has_start_position();
  if (start_position_ == NULL) {
    auto* p = CreateMaybeMessage<::roborts_decision::Point>(GetArenaNoVirtual());
    start_position_ = p;
  }
  // @@protoc_insertion_point(field_mutable:roborts_decision.MultiRobot.start_position)
  return start_position_;
}
inline void MultiRobot::set_allocated_start_position(::roborts_decision::Point* start_position) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete start_position_;
  }
  if (start_position) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      start_position = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, start_position, submessage_arena);
    }
    set_has_start_position();
  } else {
    clear_has_start_position();
  }
  start_position_ = start_position;
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.MultiRobot.start_position)
}

// -------------------------------------------------------------------

// DecisionConfig

// repeated .roborts_decision.Point point = 1;
inline int DecisionConfig::point_size() const {
  return point_.size();
}
inline void DecisionConfig::clear_point() {
  point_.Clear();
}
inline ::roborts_decision::Point* DecisionConfig::mutable_point(int index) {
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.point)
  return point_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
DecisionConfig::mutable_point() {
  // @@protoc_insertion_point(field_mutable_list:roborts_decision.DecisionConfig.point)
  return &point_;
}
inline const ::roborts_decision::Point& DecisionConfig::point(int index) const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.point)
  return point_.Get(index);
}
inline ::roborts_decision::Point* DecisionConfig::add_point() {
  // @@protoc_insertion_point(field_add:roborts_decision.DecisionConfig.point)
  return point_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
DecisionConfig::point() const {
  // @@protoc_insertion_point(field_list:roborts_decision.DecisionConfig.point)
  return point_;
}

// optional bool simulate = 2 [default = false];
inline bool DecisionConfig::has_simulate() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void DecisionConfig::set_has_simulate() {
  _has_bits_[0] |= 0x00000040u;
}
inline void DecisionConfig::clear_has_simulate() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void DecisionConfig::clear_simulate() {
  simulate_ = false;
  clear_has_simulate();
}
inline bool DecisionConfig::simulate() const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.simulate)
  return simulate_;
}
inline void DecisionConfig::set_simulate(bool value) {
  set_has_simulate();
  simulate_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.DecisionConfig.simulate)
}

// optional bool master = 3 [default = false];
inline bool DecisionConfig::has_master() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void DecisionConfig::set_has_master() {
  _has_bits_[0] |= 0x00000080u;
}
inline void DecisionConfig::clear_has_master() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void DecisionConfig::clear_master() {
  master_ = false;
  clear_has_master();
}
inline bool DecisionConfig::master() const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.master)
  return master_;
}
inline void DecisionConfig::set_master(bool value) {
  set_has_master();
  master_ = value;
  // @@protoc_insertion_point(field_set:roborts_decision.DecisionConfig.master)
}

// optional .roborts_decision.EscapeConstraint escape = 4;
inline bool DecisionConfig::has_escape() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DecisionConfig::set_has_escape() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DecisionConfig::clear_has_escape() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DecisionConfig::clear_escape() {
  if (escape_ != NULL) escape_->Clear();
  clear_has_escape();
}
inline const ::roborts_decision::EscapeConstraint& DecisionConfig::_internal_escape() const {
  return *escape_;
}
inline const ::roborts_decision::EscapeConstraint& DecisionConfig::escape() const {
  const ::roborts_decision::EscapeConstraint* p = escape_;
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.escape)
  return p != NULL ? *p : *reinterpret_cast<const ::roborts_decision::EscapeConstraint*>(
      &::roborts_decision::_EscapeConstraint_default_instance_);
}
inline ::roborts_decision::EscapeConstraint* DecisionConfig::release_escape() {
  // @@protoc_insertion_point(field_release:roborts_decision.DecisionConfig.escape)
  clear_has_escape();
  ::roborts_decision::EscapeConstraint* temp = escape_;
  escape_ = NULL;
  return temp;
}
inline ::roborts_decision::EscapeConstraint* DecisionConfig::mutable_escape() {
  set_has_escape();
  if (escape_ == NULL) {
    auto* p = CreateMaybeMessage<::roborts_decision::EscapeConstraint>(GetArenaNoVirtual());
    escape_ = p;
  }
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.escape)
  return escape_;
}
inline void DecisionConfig::set_allocated_escape(::roborts_decision::EscapeConstraint* escape) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete escape_;
  }
  if (escape) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      escape = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, escape, submessage_arena);
    }
    set_has_escape();
  } else {
    clear_has_escape();
  }
  escape_ = escape;
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.DecisionConfig.escape)
}

// repeated .roborts_decision.Point buff_point = 5;
inline int DecisionConfig::buff_point_size() const {
  return buff_point_.size();
}
inline void DecisionConfig::clear_buff_point() {
  buff_point_.Clear();
}
inline ::roborts_decision::Point* DecisionConfig::mutable_buff_point(int index) {
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.buff_point)
  return buff_point_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
DecisionConfig::mutable_buff_point() {
  // @@protoc_insertion_point(field_mutable_list:roborts_decision.DecisionConfig.buff_point)
  return &buff_point_;
}
inline const ::roborts_decision::Point& DecisionConfig::buff_point(int index) const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.buff_point)
  return buff_point_.Get(index);
}
inline ::roborts_decision::Point* DecisionConfig::add_buff_point() {
  // @@protoc_insertion_point(field_add:roborts_decision.DecisionConfig.buff_point)
  return buff_point_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
DecisionConfig::buff_point() const {
  // @@protoc_insertion_point(field_list:roborts_decision.DecisionConfig.buff_point)
  return buff_point_;
}

// optional .roborts_decision.SearchConstraint search_limit = 6;
inline bool DecisionConfig::has_search_limit() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DecisionConfig::set_has_search_limit() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DecisionConfig::clear_has_search_limit() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DecisionConfig::clear_search_limit() {
  if (search_limit_ != NULL) search_limit_->Clear();
  clear_has_search_limit();
}
inline const ::roborts_decision::SearchConstraint& DecisionConfig::_internal_search_limit() const {
  return *search_limit_;
}
inline const ::roborts_decision::SearchConstraint& DecisionConfig::search_limit() const {
  const ::roborts_decision::SearchConstraint* p = search_limit_;
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.search_limit)
  return p != NULL ? *p : *reinterpret_cast<const ::roborts_decision::SearchConstraint*>(
      &::roborts_decision::_SearchConstraint_default_instance_);
}
inline ::roborts_decision::SearchConstraint* DecisionConfig::release_search_limit() {
  // @@protoc_insertion_point(field_release:roborts_decision.DecisionConfig.search_limit)
  clear_has_search_limit();
  ::roborts_decision::SearchConstraint* temp = search_limit_;
  search_limit_ = NULL;
  return temp;
}
inline ::roborts_decision::SearchConstraint* DecisionConfig::mutable_search_limit() {
  set_has_search_limit();
  if (search_limit_ == NULL) {
    auto* p = CreateMaybeMessage<::roborts_decision::SearchConstraint>(GetArenaNoVirtual());
    search_limit_ = p;
  }
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.search_limit)
  return search_limit_;
}
inline void DecisionConfig::set_allocated_search_limit(::roborts_decision::SearchConstraint* search_limit) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete search_limit_;
  }
  if (search_limit) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      search_limit = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, search_limit, submessage_arena);
    }
    set_has_search_limit();
  } else {
    clear_has_search_limit();
  }
  search_limit_ = search_limit;
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.DecisionConfig.search_limit)
}

// optional .roborts_decision.WhirlVel whirl_vel = 7;
inline bool DecisionConfig::has_whirl_vel() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DecisionConfig::set_has_whirl_vel() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DecisionConfig::clear_has_whirl_vel() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DecisionConfig::clear_whirl_vel() {
  if (whirl_vel_ != NULL) whirl_vel_->Clear();
  clear_has_whirl_vel();
}
inline const ::roborts_decision::WhirlVel& DecisionConfig::_internal_whirl_vel() const {
  return *whirl_vel_;
}
inline const ::roborts_decision::WhirlVel& DecisionConfig::whirl_vel() const {
  const ::roborts_decision::WhirlVel* p = whirl_vel_;
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.whirl_vel)
  return p != NULL ? *p : *reinterpret_cast<const ::roborts_decision::WhirlVel*>(
      &::roborts_decision::_WhirlVel_default_instance_);
}
inline ::roborts_decision::WhirlVel* DecisionConfig::release_whirl_vel() {
  // @@protoc_insertion_point(field_release:roborts_decision.DecisionConfig.whirl_vel)
  clear_has_whirl_vel();
  ::roborts_decision::WhirlVel* temp = whirl_vel_;
  whirl_vel_ = NULL;
  return temp;
}
inline ::roborts_decision::WhirlVel* DecisionConfig::mutable_whirl_vel() {
  set_has_whirl_vel();
  if (whirl_vel_ == NULL) {
    auto* p = CreateMaybeMessage<::roborts_decision::WhirlVel>(GetArenaNoVirtual());
    whirl_vel_ = p;
  }
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.whirl_vel)
  return whirl_vel_;
}
inline void DecisionConfig::set_allocated_whirl_vel(::roborts_decision::WhirlVel* whirl_vel) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete whirl_vel_;
  }
  if (whirl_vel) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      whirl_vel = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, whirl_vel, submessage_arena);
    }
    set_has_whirl_vel();
  } else {
    clear_has_whirl_vel();
  }
  whirl_vel_ = whirl_vel;
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.DecisionConfig.whirl_vel)
}

// optional .roborts_decision.MultiRobot wing_bot = 8;
inline bool DecisionConfig::has_wing_bot() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void DecisionConfig::set_has_wing_bot() {
  _has_bits_[0] |= 0x00000008u;
}
inline void DecisionConfig::clear_has_wing_bot() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void DecisionConfig::clear_wing_bot() {
  if (wing_bot_ != NULL) wing_bot_->Clear();
  clear_has_wing_bot();
}
inline const ::roborts_decision::MultiRobot& DecisionConfig::_internal_wing_bot() const {
  return *wing_bot_;
}
inline const ::roborts_decision::MultiRobot& DecisionConfig::wing_bot() const {
  const ::roborts_decision::MultiRobot* p = wing_bot_;
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.wing_bot)
  return p != NULL ? *p : *reinterpret_cast<const ::roborts_decision::MultiRobot*>(
      &::roborts_decision::_MultiRobot_default_instance_);
}
inline ::roborts_decision::MultiRobot* DecisionConfig::release_wing_bot() {
  // @@protoc_insertion_point(field_release:roborts_decision.DecisionConfig.wing_bot)
  clear_has_wing_bot();
  ::roborts_decision::MultiRobot* temp = wing_bot_;
  wing_bot_ = NULL;
  return temp;
}
inline ::roborts_decision::MultiRobot* DecisionConfig::mutable_wing_bot() {
  set_has_wing_bot();
  if (wing_bot_ == NULL) {
    auto* p = CreateMaybeMessage<::roborts_decision::MultiRobot>(GetArenaNoVirtual());
    wing_bot_ = p;
  }
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.wing_bot)
  return wing_bot_;
}
inline void DecisionConfig::set_allocated_wing_bot(::roborts_decision::MultiRobot* wing_bot) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete wing_bot_;
  }
  if (wing_bot) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      wing_bot = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, wing_bot, submessage_arena);
    }
    set_has_wing_bot();
  } else {
    clear_has_wing_bot();
  }
  wing_bot_ = wing_bot;
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.DecisionConfig.wing_bot)
}

// optional .roborts_decision.MultiRobot master_bot = 9;
inline bool DecisionConfig::has_master_bot() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void DecisionConfig::set_has_master_bot() {
  _has_bits_[0] |= 0x00000010u;
}
inline void DecisionConfig::clear_has_master_bot() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void DecisionConfig::clear_master_bot() {
  if (master_bot_ != NULL) master_bot_->Clear();
  clear_has_master_bot();
}
inline const ::roborts_decision::MultiRobot& DecisionConfig::_internal_master_bot() const {
  return *master_bot_;
}
inline const ::roborts_decision::MultiRobot& DecisionConfig::master_bot() const {
  const ::roborts_decision::MultiRobot* p = master_bot_;
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.master_bot)
  return p != NULL ? *p : *reinterpret_cast<const ::roborts_decision::MultiRobot*>(
      &::roborts_decision::_MultiRobot_default_instance_);
}
inline ::roborts_decision::MultiRobot* DecisionConfig::release_master_bot() {
  // @@protoc_insertion_point(field_release:roborts_decision.DecisionConfig.master_bot)
  clear_has_master_bot();
  ::roborts_decision::MultiRobot* temp = master_bot_;
  master_bot_ = NULL;
  return temp;
}
inline ::roborts_decision::MultiRobot* DecisionConfig::mutable_master_bot() {
  set_has_master_bot();
  if (master_bot_ == NULL) {
    auto* p = CreateMaybeMessage<::roborts_decision::MultiRobot>(GetArenaNoVirtual());
    master_bot_ = p;
  }
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.master_bot)
  return master_bot_;
}
inline void DecisionConfig::set_allocated_master_bot(::roborts_decision::MultiRobot* master_bot) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete master_bot_;
  }
  if (master_bot) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      master_bot = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, master_bot, submessage_arena);
    }
    set_has_master_bot();
  } else {
    clear_has_master_bot();
  }
  master_bot_ = master_bot;
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.DecisionConfig.master_bot)
}

// optional .roborts_decision.Point wing_bot_task_point = 10;
inline bool DecisionConfig::has_wing_bot_task_point() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void DecisionConfig::set_has_wing_bot_task_point() {
  _has_bits_[0] |= 0x00000020u;
}
inline void DecisionConfig::clear_has_wing_bot_task_point() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void DecisionConfig::clear_wing_bot_task_point() {
  if (wing_bot_task_point_ != NULL) wing_bot_task_point_->Clear();
  clear_has_wing_bot_task_point();
}
inline const ::roborts_decision::Point& DecisionConfig::_internal_wing_bot_task_point() const {
  return *wing_bot_task_point_;
}
inline const ::roborts_decision::Point& DecisionConfig::wing_bot_task_point() const {
  const ::roborts_decision::Point* p = wing_bot_task_point_;
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.wing_bot_task_point)
  return p != NULL ? *p : *reinterpret_cast<const ::roborts_decision::Point*>(
      &::roborts_decision::_Point_default_instance_);
}
inline ::roborts_decision::Point* DecisionConfig::release_wing_bot_task_point() {
  // @@protoc_insertion_point(field_release:roborts_decision.DecisionConfig.wing_bot_task_point)
  clear_has_wing_bot_task_point();
  ::roborts_decision::Point* temp = wing_bot_task_point_;
  wing_bot_task_point_ = NULL;
  return temp;
}
inline ::roborts_decision::Point* DecisionConfig::mutable_wing_bot_task_point() {
  set_has_wing_bot_task_point();
  if (wing_bot_task_point_ == NULL) {
    auto* p = CreateMaybeMessage<::roborts_decision::Point>(GetArenaNoVirtual());
    wing_bot_task_point_ = p;
  }
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.wing_bot_task_point)
  return wing_bot_task_point_;
}
inline void DecisionConfig::set_allocated_wing_bot_task_point(::roborts_decision::Point* wing_bot_task_point) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete wing_bot_task_point_;
  }
  if (wing_bot_task_point) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      wing_bot_task_point = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, wing_bot_task_point, submessage_arena);
    }
    set_has_wing_bot_task_point();
  } else {
    clear_has_wing_bot_task_point();
  }
  wing_bot_task_point_ = wing_bot_task_point;
  // @@protoc_insertion_point(field_set_allocated:roborts_decision.DecisionConfig.wing_bot_task_point)
}

// repeated .roborts_decision.Point search_region_1 = 11;
inline int DecisionConfig::search_region_1_size() const {
  return search_region_1_.size();
}
inline void DecisionConfig::clear_search_region_1() {
  search_region_1_.Clear();
}
inline ::roborts_decision::Point* DecisionConfig::mutable_search_region_1(int index) {
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.search_region_1)
  return search_region_1_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
DecisionConfig::mutable_search_region_1() {
  // @@protoc_insertion_point(field_mutable_list:roborts_decision.DecisionConfig.search_region_1)
  return &search_region_1_;
}
inline const ::roborts_decision::Point& DecisionConfig::search_region_1(int index) const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.search_region_1)
  return search_region_1_.Get(index);
}
inline ::roborts_decision::Point* DecisionConfig::add_search_region_1() {
  // @@protoc_insertion_point(field_add:roborts_decision.DecisionConfig.search_region_1)
  return search_region_1_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
DecisionConfig::search_region_1() const {
  // @@protoc_insertion_point(field_list:roborts_decision.DecisionConfig.search_region_1)
  return search_region_1_;
}

// repeated .roborts_decision.Point search_region_2 = 12;
inline int DecisionConfig::search_region_2_size() const {
  return search_region_2_.size();
}
inline void DecisionConfig::clear_search_region_2() {
  search_region_2_.Clear();
}
inline ::roborts_decision::Point* DecisionConfig::mutable_search_region_2(int index) {
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.search_region_2)
  return search_region_2_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
DecisionConfig::mutable_search_region_2() {
  // @@protoc_insertion_point(field_mutable_list:roborts_decision.DecisionConfig.search_region_2)
  return &search_region_2_;
}
inline const ::roborts_decision::Point& DecisionConfig::search_region_2(int index) const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.search_region_2)
  return search_region_2_.Get(index);
}
inline ::roborts_decision::Point* DecisionConfig::add_search_region_2() {
  // @@protoc_insertion_point(field_add:roborts_decision.DecisionConfig.search_region_2)
  return search_region_2_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
DecisionConfig::search_region_2() const {
  // @@protoc_insertion_point(field_list:roborts_decision.DecisionConfig.search_region_2)
  return search_region_2_;
}

// repeated .roborts_decision.Point search_region_3 = 13;
inline int DecisionConfig::search_region_3_size() const {
  return search_region_3_.size();
}
inline void DecisionConfig::clear_search_region_3() {
  search_region_3_.Clear();
}
inline ::roborts_decision::Point* DecisionConfig::mutable_search_region_3(int index) {
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.search_region_3)
  return search_region_3_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
DecisionConfig::mutable_search_region_3() {
  // @@protoc_insertion_point(field_mutable_list:roborts_decision.DecisionConfig.search_region_3)
  return &search_region_3_;
}
inline const ::roborts_decision::Point& DecisionConfig::search_region_3(int index) const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.search_region_3)
  return search_region_3_.Get(index);
}
inline ::roborts_decision::Point* DecisionConfig::add_search_region_3() {
  // @@protoc_insertion_point(field_add:roborts_decision.DecisionConfig.search_region_3)
  return search_region_3_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
DecisionConfig::search_region_3() const {
  // @@protoc_insertion_point(field_list:roborts_decision.DecisionConfig.search_region_3)
  return search_region_3_;
}

// repeated .roborts_decision.Point search_region_4 = 14;
inline int DecisionConfig::search_region_4_size() const {
  return search_region_4_.size();
}
inline void DecisionConfig::clear_search_region_4() {
  search_region_4_.Clear();
}
inline ::roborts_decision::Point* DecisionConfig::mutable_search_region_4(int index) {
  // @@protoc_insertion_point(field_mutable:roborts_decision.DecisionConfig.search_region_4)
  return search_region_4_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >*
DecisionConfig::mutable_search_region_4() {
  // @@protoc_insertion_point(field_mutable_list:roborts_decision.DecisionConfig.search_region_4)
  return &search_region_4_;
}
inline const ::roborts_decision::Point& DecisionConfig::search_region_4(int index) const {
  // @@protoc_insertion_point(field_get:roborts_decision.DecisionConfig.search_region_4)
  return search_region_4_.Get(index);
}
inline ::roborts_decision::Point* DecisionConfig::add_search_region_4() {
  // @@protoc_insertion_point(field_add:roborts_decision.DecisionConfig.search_region_4)
  return search_region_4_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::roborts_decision::Point >&
DecisionConfig::search_region_4() const {
  // @@protoc_insertion_point(field_list:roborts_decision.DecisionConfig.search_region_4)
  return search_region_4_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace roborts_decision

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_decision_2eproto
